[platformio]
description = VCNL4040_DS28E18 Library Examples
default_envs = pico
src_dir = example/VL53L1X_DS28E18_Example

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    symlink://.
    #https://github.com/DanielSart/DS28E18_DS2482_Library.git
    symlink:///Users/kaikuklok/DS28E18_DS2482_Library #use for local development, when changing stuff in the library locally
    adafruit/Adafruit DS248x @ ^1.0.1
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
lib_ldf_mode = deep+

[env:pico]
platform = raspberrypi
board = pico

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:nanoRP2040]
board = nanorp2040connect
platform = raspberrypi
framework = arduino
build_flags = 
	-D ARDUINO_ARCH_RP2040
build_unflags = 
	-DUSE_TINYUSB
board_build.mcu = RP2040

[env:nano33iot]
board = nano_33_iot
framework = arduino
board_build.mcu = SAMD21
platform = atmelsam
